{
  "formatVersion": "1.1",
  "component": {
    "group": "com.energy.sdk",
    "module": "qx-hybrid",
    "version": "0.1.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "com.journeyapps",
          "module": "zxing-android-embedded",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "com.github.aicareles",
          "module": "Android-BLE",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "qx-hybrid-0.1.10.aar",
          "url": "qx-hybrid-0.1.10.aar",
          "size": 286882,
          "sha512": "25329e11d1e6c8c822da38604e7703de96b3d2cbc86cbf328024bcf6904db16ccee6f51ec51f9cd1ebd0cd1de8dda4308a4fc5edc412da4f829073d37c65e3b0",
          "sha256": "346be25a99a7070fe5aa57bc707ea201dddbc6959c1de9e76b32436fcac77167",
          "sha1": "4cc1995e788605da1fb50385cd144d8fc54cbce9",
          "md5": "498b25e2f79c3429c6053ce108dcccfa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "com.journeyapps",
          "module": "zxing-android-embedded",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "com.github.aicareles",
          "module": "Android-BLE",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "qx-hybrid-0.1.10.aar",
          "url": "qx-hybrid-0.1.10.aar",
          "size": 286882,
          "sha512": "25329e11d1e6c8c822da38604e7703de96b3d2cbc86cbf328024bcf6904db16ccee6f51ec51f9cd1ebd0cd1de8dda4308a4fc5edc412da4f829073d37c65e3b0",
          "sha256": "346be25a99a7070fe5aa57bc707ea201dddbc6959c1de9e76b32436fcac77167",
          "sha1": "4cc1995e788605da1fb50385cd144d8fc54cbce9",
          "md5": "498b25e2f79c3429c6053ce108dcccfa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qx-hybrid-0.1.10-sources.jar",
          "url": "qx-hybrid-0.1.10-sources.jar",
          "size": 99835,
          "sha512": "cedbf7c841965fef5a8dac3b088dd7ae2e265109a89ce47ed0b9d67df96fc6f9e8a483518a256af9d9a4dd5d9b8f3bb4fdc7c2d1a905dc131169e7047f1d1910",
          "sha256": "8d83e8e0d41f38bb67f0a562c7684a27582d687c5c3184738d615514baf9266b",
          "sha1": "51f5664239c73c74b38ce4cfaf5c2d0d25f7aa4b",
          "md5": "6fe6be879656713c2b4cbfcb508b1a0e"
        }
      ]
    }
  ]
}
