{
  "formatVersion": "1.1",
  "component": {
    "group": "com.energy.sdk",
    "module": "qx-hybrid",
    "version": "0.1.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "com.journeyapps",
          "module": "zxing-android-embedded",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "com.github.aicareles",
          "module": "Android-BLE",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "qx-hybrid-0.1.10.aar",
          "url": "qx-hybrid-0.1.10.aar",
          "size": 277762,
          "sha512": "4bc0fa68588209e30ac4210c3c0cfe6d20f1a2a39ac7cd6ffb4e2feec971afee856c2c5f36e3d8408a8a103c10cf049ce75fba3273dccbcb2e968a7e10e2f32b",
          "sha256": "fc7814964b8c5929cf93e082471a102d508308dae9569a46f071c1f291d3b68a",
          "sha1": "43a12d2fe747955e60eee3eaa04f03a8937a2379",
          "md5": "49ef89d31e56543c0c1dfea614923eee"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "com.journeyapps",
          "module": "zxing-android-embedded",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "com.github.aicareles",
          "module": "Android-BLE",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "qx-hybrid-0.1.10.aar",
          "url": "qx-hybrid-0.1.10.aar",
          "size": 277762,
          "sha512": "4bc0fa68588209e30ac4210c3c0cfe6d20f1a2a39ac7cd6ffb4e2feec971afee856c2c5f36e3d8408a8a103c10cf049ce75fba3273dccbcb2e968a7e10e2f32b",
          "sha256": "fc7814964b8c5929cf93e082471a102d508308dae9569a46f071c1f291d3b68a",
          "sha1": "43a12d2fe747955e60eee3eaa04f03a8937a2379",
          "md5": "49ef89d31e56543c0c1dfea614923eee"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qx-hybrid-0.1.10-sources.jar",
          "url": "qx-hybrid-0.1.10-sources.jar",
          "size": 93589,
          "sha512": "0d3f6fc38f8f8926821756d8e5eab1c3be20be30e5667d6280c5e9b4d652a3e4db25af1a729e3fcafe81c42cd754950a12b5c4aeafbe1c30784de9f926ddc32b",
          "sha256": "205e12484a56ba8d54df2427a7bc172c514ca07e9fccc90acea29aa5efee44f8",
          "sha1": "e7518b1cc28df620146ae96715ec8f2f738cb247",
          "md5": "21d67a7d150c7c60ef08d133fc5af0f3"
        }
      ]
    }
  ]
}
