{
  "formatVersion": "1.1",
  "component": {
    "group": "com.energy.sdk",
    "module": "qx-hybrid",
    "version": "0.1.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "com.journeyapps",
          "module": "zxing-android-embedded",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "com.github.aicareles",
          "module": "Android-BLE",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "qx-hybrid-0.1.10.aar",
          "url": "qx-hybrid-0.1.10.aar",
          "size": 285324,
          "sha512": "b56485b6fdd6bf62e34faaec2ae3899b249a79c033a1d098c10471106aad179d79b7c0158d31649cffe40096e7182530f7c4045f3fe14374729e23cfd9db03b2",
          "sha256": "897436c3162784350d0f24a18072ce5c999dd62639a957b358ec34b034891c98",
          "sha1": "721a5cd5dd49c11d8ba808f9ca75d2ef17d70bb4",
          "md5": "3027b50fdd364cacd438a16305e3b004"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "com.journeyapps",
          "module": "zxing-android-embedded",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "com.github.aicareles",
          "module": "Android-BLE",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "qx-hybrid-0.1.10.aar",
          "url": "qx-hybrid-0.1.10.aar",
          "size": 285324,
          "sha512": "b56485b6fdd6bf62e34faaec2ae3899b249a79c033a1d098c10471106aad179d79b7c0158d31649cffe40096e7182530f7c4045f3fe14374729e23cfd9db03b2",
          "sha256": "897436c3162784350d0f24a18072ce5c999dd62639a957b358ec34b034891c98",
          "sha1": "721a5cd5dd49c11d8ba808f9ca75d2ef17d70bb4",
          "md5": "3027b50fdd364cacd438a16305e3b004"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qx-hybrid-0.1.10-sources.jar",
          "url": "qx-hybrid-0.1.10-sources.jar",
          "size": 98274,
          "sha512": "33f343e6e21055cc75c6b22a92e632e1b524fdcc1f522855744c596a092ef1cafb54be519494ba20372285724cb62a02dae2f1afd354bc564da72b73cd8419af",
          "sha256": "d55e679445545dfff56468b8b0e87017677df20d51838bd0bcbe249b34de2b34",
          "sha1": "9de4c5c100c71cae4e084476143981841278bcd4",
          "md5": "d21e57538c7166c87c5e80334f1c3308"
        }
      ]
    }
  ]
}
