{
  "formatVersion": "1.1",
  "component": {
    "group": "com.energy.sdk",
    "module": "qx-hybrid",
    "version": "0.1.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "com.journeyapps",
          "module": "zxing-android-embedded",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "com.github.aicareles",
          "module": "Android-BLE",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "qx-hybrid-0.1.12.aar",
          "url": "qx-hybrid-0.1.12.aar",
          "size": 291792,
          "sha512": "3b4013309f2375a17661589af168f9da87bae776a8c749fcd282efe2db9250db7dbeb347c592bb086af1059c0e4f1b322065d66b37adbe6aa9024c5844ab8743",
          "sha256": "0f2d910cad1cb00127bff7152347ac0cc4e43e979324a0f6d6be05673257d7a6",
          "sha1": "00d9788071c7736a78da9110d7cc9fb0488dd082",
          "md5": "fcb7b196bd773189a42f9837a8e0975f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "com.journeyapps",
          "module": "zxing-android-embedded",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "com.github.aicareles",
          "module": "Android-BLE",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "qx-hybrid-0.1.12.aar",
          "url": "qx-hybrid-0.1.12.aar",
          "size": 291792,
          "sha512": "3b4013309f2375a17661589af168f9da87bae776a8c749fcd282efe2db9250db7dbeb347c592bb086af1059c0e4f1b322065d66b37adbe6aa9024c5844ab8743",
          "sha256": "0f2d910cad1cb00127bff7152347ac0cc4e43e979324a0f6d6be05673257d7a6",
          "sha1": "00d9788071c7736a78da9110d7cc9fb0488dd082",
          "md5": "fcb7b196bd773189a42f9837a8e0975f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qx-hybrid-0.1.12-sources.jar",
          "url": "qx-hybrid-0.1.12-sources.jar",
          "size": 100932,
          "sha512": "49ec6d90732dfcd839526112ff0ce582482ab64a8b355b309c69c509e4f10b04d902ecfc488605cd7595877b2c9d85de235999cef2065cdb31fb791e6fd61488",
          "sha256": "1cea48693158675c2f1ebc328f2ff7e87bfb4c417c0988a62932e636f06adb1d",
          "sha1": "28318b9121082101e77810a5ffc7c0016ad4ed46",
          "md5": "ccfe3647a2d40209f04c3840580ac7cf"
        }
      ]
    }
  ]
}
