{
  "formatVersion": "1.1",
  "component": {
    "group": "com.energy.sdk",
    "module": "qx-hybrid",
    "version": "0.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "com.journeyapps",
          "module": "zxing-android-embedded",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "com.github.aicareles",
          "module": "Android-BLE",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "qx-hybrid-0.1.8.aar",
          "url": "qx-hybrid-0.1.8.aar",
          "size": 276883,
          "sha512": "767d29e36042fa98db9487ff166ae1805c932e921a5f387e8b0ec8e20355ae188359297d99dd6cc71551f666c35d334f4c9ddba0ef28e8a3f16650dfa15adfbc",
          "sha256": "effb28dfc596f7c573728a9ca4aa6a28ebcfa09df9feaf8a54e6e715a3f934a2",
          "sha1": "6c8e0adb1e80e8469031e08a6ad86e0c365280f9",
          "md5": "c30f9fe51b602b3418dfe1e03cf83191"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "com.journeyapps",
          "module": "zxing-android-embedded",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "com.github.aicareles",
          "module": "Android-BLE",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "qx-hybrid-0.1.8.aar",
          "url": "qx-hybrid-0.1.8.aar",
          "size": 276883,
          "sha512": "767d29e36042fa98db9487ff166ae1805c932e921a5f387e8b0ec8e20355ae188359297d99dd6cc71551f666c35d334f4c9ddba0ef28e8a3f16650dfa15adfbc",
          "sha256": "effb28dfc596f7c573728a9ca4aa6a28ebcfa09df9feaf8a54e6e715a3f934a2",
          "sha1": "6c8e0adb1e80e8469031e08a6ad86e0c365280f9",
          "md5": "c30f9fe51b602b3418dfe1e03cf83191"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qx-hybrid-0.1.8-sources.jar",
          "url": "qx-hybrid-0.1.8-sources.jar",
          "size": 93104,
          "sha512": "790dee0752659c9f7d254b5081c82d61d79db205a8b203012e67abb807a83919528e346f76070cbca3e2883f124c39ef844f1c00bff5cc868e3f8c468e43920f",
          "sha256": "1f4145a58ba603060c8a0e45b82902b147fb9bd6fb426ddcd7fe77f63329ff18",
          "sha1": "0bfdaa586991f6cbfdac4ef5dcad1584b128a8e7",
          "md5": "a56c75e6801a72ea8480bfdf9f637904"
        }
      ]
    }
  ]
}
