{
  "formatVersion": "1.1",
  "component": {
    "group": "com.energy.sdk",
    "module": "qx-hybrid",
    "version": "0.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "com.journeyapps",
          "module": "zxing-android-embedded",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "com.github.aicareles",
          "module": "Android-BLE",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "qx-hybrid-0.1.9.aar",
          "url": "qx-hybrid-0.1.9.aar",
          "size": 286770,
          "sha512": "1b9a084d2d80d3ffe3be483fcbee2f695b46263fbc1178fb8b6abe888c8604af20902bbe91d9ae65d8dde92e1e8bdfae7a3a46ca3a9252abed26d8124070fe44",
          "sha256": "42c14af46d13e99d1f29e9f0d9cff6de9b9f2ce20b1a830e23d3ef9ab2b64745",
          "sha1": "873a50d5560b9728c371d5afdad77f15ad7b52bf",
          "md5": "25a642da14767200429d84a878e684a0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "com.journeyapps",
          "module": "zxing-android-embedded",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "com.github.aicareles",
          "module": "Android-BLE",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "qx-hybrid-0.1.9.aar",
          "url": "qx-hybrid-0.1.9.aar",
          "size": 286770,
          "sha512": "1b9a084d2d80d3ffe3be483fcbee2f695b46263fbc1178fb8b6abe888c8604af20902bbe91d9ae65d8dde92e1e8bdfae7a3a46ca3a9252abed26d8124070fe44",
          "sha256": "42c14af46d13e99d1f29e9f0d9cff6de9b9f2ce20b1a830e23d3ef9ab2b64745",
          "sha1": "873a50d5560b9728c371d5afdad77f15ad7b52bf",
          "md5": "25a642da14767200429d84a878e684a0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qx-hybrid-0.1.9-sources.jar",
          "url": "qx-hybrid-0.1.9-sources.jar",
          "size": 99630,
          "sha512": "b7bc0fc70bbc935a99f896ac624d798245f47ae9df2d89fe7a012d215635c358b7183def670bdafd8231053ad3a9b58c59f7d20e2b161c4cc831920bd811f204",
          "sha256": "b0e8092242d75a631302aee90427173b50cb1fb90f66ec19ef7e801f16e2f6c7",
          "sha1": "aafe3a5a77856496ffd2c78facf2699719aa04bb",
          "md5": "c9dbd7be55c2acf5d1d362cbbc032401"
        }
      ]
    }
  ]
}
