{
  "formatVersion": "1.1",
  "component": {
    "group": "com.energy.sdk",
    "module": "qx-hybrid",
    "version": "0.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "com.journeyapps",
          "module": "zxing-android-embedded",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "com.github.aicareles",
          "module": "Android-BLE",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "qx-hybrid-0.1.9.aar",
          "url": "qx-hybrid-0.1.9.aar",
          "size": 277376,
          "sha512": "622015c268eac7717cb65921d8d49cf272387a734747c87403b6ec1fe913d3d94e1098805325eaeafe9ebdc13a576dbd726335a85798aa94703061c951db8298",
          "sha256": "df4eebdfd475cc06d5ec91eca9ccf4bbade22f5d22cf87a735ce350a463b507a",
          "sha1": "ecf6455092faf24c0a8466864a52d5fdc34ad160",
          "md5": "2a7fd8061b9bb4001ae79198057854f2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "com.journeyapps",
          "module": "zxing-android-embedded",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "com.github.aicareles",
          "module": "Android-BLE",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "qx-hybrid-0.1.9.aar",
          "url": "qx-hybrid-0.1.9.aar",
          "size": 277376,
          "sha512": "622015c268eac7717cb65921d8d49cf272387a734747c87403b6ec1fe913d3d94e1098805325eaeafe9ebdc13a576dbd726335a85798aa94703061c951db8298",
          "sha256": "df4eebdfd475cc06d5ec91eca9ccf4bbade22f5d22cf87a735ce350a463b507a",
          "sha1": "ecf6455092faf24c0a8466864a52d5fdc34ad160",
          "md5": "2a7fd8061b9bb4001ae79198057854f2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qx-hybrid-0.1.9-sources.jar",
          "url": "qx-hybrid-0.1.9-sources.jar",
          "size": 93252,
          "sha512": "5e22504b0128d2ec14baf3947e7b0f351f5029d1f73c4dfc857c66d733596623f2e5f89e6fda9cee5e2fbb85455fa12c21a488ab97815b11e83be533b55d251e",
          "sha256": "7c2b1e178766345ad13398ad2a34bb6686166b44a2e78d6a1a71565d75e20802",
          "sha1": "ad4da45e921606c2c028dc09a5204b5fa47d8891",
          "md5": "b1fcd00a38b76ab0c2013e12dd09c7f0"
        }
      ]
    }
  ]
}
