{
  "formatVersion": "1.1",
  "component": {
    "group": "com.energy.sdk",
    "module": "qx-hybrid",
    "version": "0.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "com.journeyapps",
          "module": "zxing-android-embedded",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "com.github.aicareles",
          "module": "Android-BLE",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "qx-hybrid-0.1.9.aar",
          "url": "qx-hybrid-0.1.9.aar",
          "size": 277762,
          "sha512": "4bc0fa68588209e30ac4210c3c0cfe6d20f1a2a39ac7cd6ffb4e2feec971afee856c2c5f36e3d8408a8a103c10cf049ce75fba3273dccbcb2e968a7e10e2f32b",
          "sha256": "fc7814964b8c5929cf93e082471a102d508308dae9569a46f071c1f291d3b68a",
          "sha1": "43a12d2fe747955e60eee3eaa04f03a8937a2379",
          "md5": "49ef89d31e56543c0c1dfea614923eee"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "com.journeyapps",
          "module": "zxing-android-embedded",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "com.github.aicareles",
          "module": "Android-BLE",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "qx-hybrid-0.1.9.aar",
          "url": "qx-hybrid-0.1.9.aar",
          "size": 277762,
          "sha512": "4bc0fa68588209e30ac4210c3c0cfe6d20f1a2a39ac7cd6ffb4e2feec971afee856c2c5f36e3d8408a8a103c10cf049ce75fba3273dccbcb2e968a7e10e2f32b",
          "sha256": "fc7814964b8c5929cf93e082471a102d508308dae9569a46f071c1f291d3b68a",
          "sha1": "43a12d2fe747955e60eee3eaa04f03a8937a2379",
          "md5": "49ef89d31e56543c0c1dfea614923eee"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qx-hybrid-0.1.9-sources.jar",
          "url": "qx-hybrid-0.1.9-sources.jar",
          "size": 93484,
          "sha512": "c6ae814fa895dd87ea0461fce2214124ec88c6a14469fbf429790adde7168a52008b6b322de41b893d9ff823bdccd0bfd73c84559d11caf19042391f9653c3ef",
          "sha256": "c8f0e5794ba6b00d897b3349e063d3847a800cc3d884c4dfbf62205d1e9387ce",
          "sha1": "9048f4915bd6298e49a0dee8dd8965fa22607e77",
          "md5": "6f12b06e9252ddb33e2dc0b491f45787"
        }
      ]
    }
  ]
}
