{
  "formatVersion": "1.1",
  "component": {
    "group": "com.energy.sdk",
    "module": "qx-hybrid",
    "version": "0.1.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "com.journeyapps",
          "module": "zxing-android-embedded",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "com.github.aicareles",
          "module": "Android-BLE",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "qx-hybrid-0.1.11.aar",
          "url": "qx-hybrid-0.1.11.aar",
          "size": 284273,
          "sha512": "ad7fc92939e913ca284a1988581f761cee7329ad0fcb5107b145fd8999171faa0cb0138113b126a073df60c7fec5d8a2a6eada27f8fedecea32f84079c0276db",
          "sha256": "febfcdcebd16ecc7da054d16a958e92b6bbfb1a03c45db1e47e7dbaadd6fc6fe",
          "sha1": "78532ce8baebd1a6ff69bf4c442b0c46c8031538",
          "md5": "83bd1da4d0586eca93d10d24e5c1fd41"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "com.journeyapps",
          "module": "zxing-android-embedded",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "com.github.aicareles",
          "module": "Android-BLE",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "qx-hybrid-0.1.11.aar",
          "url": "qx-hybrid-0.1.11.aar",
          "size": 284273,
          "sha512": "ad7fc92939e913ca284a1988581f761cee7329ad0fcb5107b145fd8999171faa0cb0138113b126a073df60c7fec5d8a2a6eada27f8fedecea32f84079c0276db",
          "sha256": "febfcdcebd16ecc7da054d16a958e92b6bbfb1a03c45db1e47e7dbaadd6fc6fe",
          "sha1": "78532ce8baebd1a6ff69bf4c442b0c46c8031538",
          "md5": "83bd1da4d0586eca93d10d24e5c1fd41"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qx-hybrid-0.1.11-sources.jar",
          "url": "qx-hybrid-0.1.11-sources.jar",
          "size": 97607,
          "sha512": "a0fcfdeb27bceb0706cbca63cad35860a644dfae0450d127eea9e52fb417ff8305763bb1c85f63ca6a44bea9fc274046d90f8679913ec17071df4ce84ffd10cc",
          "sha256": "352c41a37d4834da494b7151b436c3e2c3c4a37b59ee1951d477d5cdf67c753a",
          "sha1": "f18672e1c93a59f2a5891f197250cb22c4b8651b",
          "md5": "a96a0b448b6b747a8acb493b3406c409"
        }
      ]
    }
  ]
}
